name: Build and Sign

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: "The release version"
        required: true
        default: "0.0.0"
        type: string
      betaversion:
        description: "The beta version"
        required: false
        default: ""
        type: string

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup DepotDownloader
        run: |
          wget https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.7.2/DepotDownloader-linux-x64.zip
          unzip DepotDownloader-linux-x64.zip
          chmod +x DepotDownloader

      - name: Generate auth code
        id: generate
        uses: CyberAndrii/steam-totp@c7f636bc64e77f1b901e0420b7890813141508ee
        with:
          shared_secret: ${{ secrets.STEAM_SHARED_SECRET }}

      - name: Download PlateUp Files
        run: |
          ./DepotDownloader -app 1599600 -depot 1599601 -username ${{ secrets.STEAM_USERNAME }} -password ${{ secrets.STEAM_PASSWORD }} <<< "${{ steps.generate.outputs.code }}"

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.x

      - name: Build the application
        run: |
          set -x
          dotnet build -c Workshop -p:GamePath=`ls -d $PWD/depots/1599601/**`/PlateUp -p:EnableModDeployLocal='false' -p:EnableGameDebugging='false' --os windows --no-self-contained ./KitchenLib.csproj
          mkdir ./content/
          cp ./bin/Workshop/net472/windows-x64/KitchenLib-Workshop.dll ./content/
          cp ./bin/Workshop/net472/windows-x64/KitchenLib-Workshop.pdb ./content/
          cp ./bin/Workshop/net472/KitchenLib-Workshop.xml ./content/
          cp "./UnityProject - KitchenLib/content/mod.assets" ./content/KitchenLib-Workshop.assets

      - name: cosign-installer
        uses: sigstore/cosign-installer@v3.3.0

      - name: Sign with Github Key
        run: |
          cosign sign-blob --yes ./content/KitchenLib-Workshop.dll --bundle ./content/cosign.bundle

      - name: Perform Hashes
        run: |
          sha256sum ./content/* > ./content/checksums.txt
          ls ./content/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: KitchenLib-Build
          path: content/
          if-no-files-found: error

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v${{ github.event.inputs.releaseversion }}${{ github.event.inputs.betaversion }}
          release_name: v${{ github.event.inputs.releaseversion }}${{ github.event.inputs.betaversion }}
          body_path: ./Changelogs/${{ github.event.inputs.releaseversion }}/Github/v${{ github.event.inputs.releaseversion }}${{ github.event.inputs.betaversion }}.MD
          draft: false
          prerelease: ${{ !(github.event.inputs.betaversion == '') }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: KitchenLib-Build
          path: build

      - name: Display structure of downloaded files
        run: |
          cd build
          zip -r KitchenLib-Build.zip *

      - name: Upload Release Files
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/KitchenLib-Build.zip
          asset_name: KitchenLib-v${{ github.event.inputs.releaseversion }}${{ github.event.inputs.betaversion }}}.zip
          asset_content_type: application/zip
