name: Build KitchenLib for Workshop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Workshop]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: KitchenLib.sln                        # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: KitchenLib.TestMod/KitchenLib.TestMod.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
         
    - name: Setup DepotDownloader
      run: |
         Invoke-WebRequest https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.5.0/DepotDownloader-windows-x64.zip -OutFile out.zip
         7z x out.zip
        
    - name: Generate auth code
      id: generate
      uses: CyberAndrii/steam-totp@c7f636bc64e77f1b901e0420b7890813141508ee
      with:
        shared_secret: ${{ secrets.STEAM_SHARED_SECRET }}
        
    - name: Download PlateUp Files
      run: |
         "${{ steps.generate.outputs.code }}" | .\DepotDownloader.exe -app 1599600 -depot 1599601 -username ${{ secrets.STEAM_USERNAME }} -password ${{ secrets.STEAM_PASSWORD }}
         
     # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
         5.0.x
         
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build the application
      run: |
        $id = ls -Directory -Name $PWD/depots/1599601/
        ls $PWD/depots/1599601/$id/PlateUp
        msbuild $env:Solution_Name -r /p:Configuration=$env:Configuration /p:EnableModDeployLocal='true' /p:GamePath=$PWD/depots/1599601/$id/PlateUp
      env:
        Configuration: ${{ matrix.configuration }}
    - name: test
      run: ls ./KitchenLib/content/

    # Upload the build artifacts for later use
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Workshop Build
        path: KitchenLib/content/
        if-no-files-found: error
